services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      chmod +x setup.sh
      ./setup.sh
      
    startCommand: gunicorn app:app
